# Generated by Django 4.1.2 on 2022-10-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("age", models.IntegerField()),
                ("student_class", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
            ],
            options={"db_table": "Student",},
        ),
    ]
