# Generated by Django 4.1.2 on 2022-10-22 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
            ],
            options={"db_table": "parent",},
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
            options={"db_table": "subject",},
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.CheckConstraint(
                check=models.Q(("age__gt", 5)), name="age greater than 5"
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.CheckConstraint(
                check=models.Q(("student_class__gt", 0)), name="class greater than 0"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student",
                to="student.parent",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="subject",
            field=models.ManyToManyField(related_name="student", to="student.subject"),
        ),
    ]
