# Generated by Django 4.1.2 on 2022-10-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_parent_subject_student_age greater than 5_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="subject",
            field=models.ManyToManyField(related_name="students", to="student.subject"),
        ),
    ]
