# Generated by Django 4.1.2 on 2022-10-22 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_alter_student_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="student.parent",
            ),
        ),
    ]
