# Generated by Django 4.1.2 on 2022-10-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0006_token_remove_student_email_user_parent_user_data"),
    ]

    operations = [
        migrations.RemoveField(model_name="parent", name="user_data",),
        migrations.DeleteModel(name="User",),
    ]
