# Generated by Django 4.1.2 on 2022-10-28 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0007_remove_parent_user_data_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="password",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="parent",
            name="token_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student.token",
            ),
        ),
        migrations.AddField(
            model_name="parent",
            name="username",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="password",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="token_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student.token",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="username",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
