# Generated by Django 4.1.2 on 2022-10-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0008_parent_password_parent_token_id_parent_username_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parent", old_name="token_id", new_name="token",
        ),
        migrations.RenameField(
            model_name="student", old_name="token_id", new_name="token",
        ),
    ]
