# Generated by Django 4.1.2 on 2022-10-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0009_rename_token_id_parent_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student", name="age", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_class",
            field=models.IntegerField(null=True),
        ),
    ]
